[workspace]
allow_dirty = false
changelog_update = true
dependencies_update = false
features_always_increment_minor = false
git_release_enable = false
git_tag_enable = false
pr_branch_prefix = "release-plz-"
pr_draft = false
pr_labels = ["release"]
publish = false
release_always = false
semver_check = true

[[package]]
name = "xtask"
release = false

[changelog]
protect_breaking_commits = true
sort_commits = "oldest"
tag_pattern = "^v[0-9]+\\.[0-9]+\\.[0-9]+$"
body = """
## [{{ version }}] - {{ timestamp | date(format="%Y-%m-%d") }}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}

{% for commit in commits %}
{%- if commit.scope -%}
- *({{ commit.scope }})* {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }}{%- if commit.links %} ({% for link in commit.links %}[{{ link.text }}]({{ link.href }}) {% endfor -%}){% endif %}
{% else -%}
- {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }}
{% endif -%}
{% endfor -%}
{% endfor %}
"""
