[package]
name = "xtask"
version = "0.0.0"
edition = "2024"
publish = false

[lints]
workspace = true

[dependencies]
thiserror = "2"

[target.'cfg(windows)'.dependencies]
restart-manager = { path = ".." }
windows-sys = { version = "0.61", features = [
    "Win32_System_Console",
    "Win32_System_Threading",
] }
